jwt:
  expiration: 86400000
  secret: mySecretKeyForJWTShouldBeAtLeast256BitsLongForHS256Algorithm
logging:
  level:
    ir:
      kghobad: DEBUG
spring:
  application:
    name: thesis-defense-time-schedular
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true  # Allow remote access
        trace: false
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.MySQLDialect
#      jakarta:
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-target: src/main/resources/db/migration/V1__initial_schema.sql
    show-sql: true
    defer-datasource-initialization: true
  liquibase.enabled: false
  sql:
    init:
      mode: embedded
      data-locations: classpath:data-dev.sql
server:
  servlet:
    context-path: /api/v1
frontend:
  url: http://localhost:3000
rate-limit:
  max-submitted-forms: 3
