app.max-future-days: 30
jwt:
  expiration: 86400000
  secret: mySecretKeyForJWTShouldBeAtLeast256BitsLongForHS256Algorithm
  refresh:
    expiration: 604800000
logging:
  level:
    ir:
      kghobad: DEBUG
spring:
  application:
    name: thesis-defense-time-schedular
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true  # Allow remote access
        trace: false
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  liquibase.enabled: false
  sql:
    init:
      mode: embedded
      data-locations: classpath:data-dev.sql
server:
  servlet:
    context-path: /api/v1
frontend:
  url: http://localhost:3000
rate-limit:
  max-submitted-forms: 3
